// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
//Example:
/// ```dart
//import 'firebase_options.dart';

//await Firebase.initializeApp(
//options: DefaultFirebaseOptions.currentPlatform,
//);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa0idiMMN14ba1StAS6dHxufzxkvUb0Gg',
    appId: '1:968414616965:android:e0f3fcbca797f5ebb0f8ec',
    messagingSenderId: '968414616965',
    projectId: 'turismo-colombiapp',
    storageBucket: 'turismo-colombiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq2iS0Roo7EKPyXMocdd099gaV849vr2c',
    appId: '1:968414616965:ios:76c69c8047dd2c34b0f8ec',
    messagingSenderId: '968414616965',
    projectId: 'turismo-colombiapp',
    storageBucket: 'turismo-colombiapp.appspot.com',
    iosClientId:
        '968414616965-6gfavre1n1h63u7de72vdi7fvs78p2jk.apps.googleusercontent.com',
    iosBundleId: 'edu.UdA.turismoColombia',
  );
}
